import os
from typing import List, Dict, Any
from ebooklib import epub
import markdown2
import re
from datetime import datetime

class NovelExporter:
    def __init__(self, output_dir: str = "novel_output/exports"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def _clean_markdown_for_txt(self, text: str) -> str:
        """
        Convert Markdown to platform-ready TXT (Qidian/Jinjiang style).
        1. Remove **bold**, *italic*
        2. Remove # Headers (convert to lines)
        3. Ensure 2 spaces indentation for paragraphs
        """
        # Remove bold/italic markers
        text = text.replace("**", "").replace("*", "")
        
        # Remove headers but keep text
        text = re.sub(r'^#+\s+(.*)$', r'\1', text, flags=re.MULTILINE)
        
        # Normalize newlines
        lines = text.split('\n')
        formatted_lines = []
        for line in lines:
            line = line.strip()
            if line:
                # Standard Chinese novel indentation (2 full-width spaces)
                formatted_lines.append(f"　　{line}")
            else:
                formatted_lines.append("") # Keep empty lines for spacing
        
        return "\n".join(formatted_lines)

    def generate_txt(self, title: str, chapters: List[Dict[str, Any]]) -> str:
        """Generate a single TXT file for the entire range."""
        filename = f"{title}_{datetime.now().strftime('%Y%m%d_%H%M')}.txt"
        filepath = os.path.join(self.output_dir, filename)
        
        content = []
        content.append(f"《{title}》")
        content.append(f"Generated by Infinite-Flow Writer")
        content.append("-" * 20 + "\n")
        
        for ch in chapters:
            content.append(f"第{ch['num']}章 {ch.get('title', '')}")
            content.append(self._clean_markdown_for_txt(ch['content']))
            content.append("\n" + "-" * 10 + "\n")
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write("\n".join(content))
            
        return filepath

    def generate_epub(self, title: str, author: str, chapters: List[Dict[str, Any]]) -> str:
        """Generate a standard EPUB file."""
        book = epub.EpubBook()
        
        # Metadata
        book.set_identifier(f'id_{datetime.now().strftime("%Y%m%d")}')
        book.set_title(title)
        book.set_language('zh')
        book.add_author(author)
        
        # Create Chapters
        epub_chapters = []
        for ch in chapters:
            # Convert MD to HTML
            html_content = markdown2.markdown(ch['content'])
            
            c = epub.EpubHtml(title=f"第{ch['num']}章", file_name=f"chap_{ch['num']}.xhtml", lang='zh')
            c.content = f"<h1>第{ch['num']}章 {ch.get('title', '')}</h1>{html_content}"
            book.add_item(c)
            epub_chapters.append(c)
            
        # Define Table of Contents
        book.toc = (epub_chapters)
        
        # Add default NCX and Nav
        book.add_item(epub.EpubNcx())
        book.add_item(epub.EpubNav())
        
        # Define CSS style
        style = 'body { font-family: "Source Han Serif SC", serif; } h1 { text-align: center; } p { text-indent: 2em; margin-bottom: 0.5em; }'
        nav_css = epub.EpubItem(uid="style_nav", file_name="style/nav.css", media_type="text/css", content=style)
        book.add_item(nav_css)
        
        # Spine
        book.spine = ['nav'] + epub_chapters
        
        # Write
        filename = f"{title}_{datetime.now().strftime('%Y%m%d_%H%M')}.epub"
        filepath = os.path.join(self.output_dir, filename)
        epub.write_epub(filepath, book, {{}})
        
        return filepath
